imagePullSecrets: []

replicaCount: 1

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix

frontend:
  enabled: true
  image:
    repository: registry.gitlab.com/eagledevstack/mousebook-web
    pullPolicy: IfNotPresent
    tag: "3b3a275e"
  type: ClusterIP
  protocol: TCP
  port: 3001
  targetPort: 3001
  volumeMounts: []
  resources: {}

auth:
  image:
    repository: registry.gitlab.com/eagledevstack/mousebook-auth
    pullPolicy: IfNotPresent
    tag: "7dab3b5b"
  volumeMounts: []
  resources: {}

api:
  image:
    repository: registry.gitlab.com/eagledevstack/mousebook-api
    pullPolicy: IfNotPresent
    tag: "70e86276"
  volumeMounts: []
  resources: {}

postgres:
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "17"
  volumeMounts: []
  resources: {}

redis:
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "8"
  volumeMounts: []
  resources: {}

secretRef: ""

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}
